table Sheet1
	lineageTag: acd9afc9-760a-4182-86c7-9fde2ba6546a

	column Segment
		dataType: string
		lineageTag: ba4493dd-4e31-4414-9d0b-ca9bf0660def
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 068f9cd0-d738-4303-bb37-e6450f67536c
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column Product
		dataType: string
		lineageTag: ee1480bf-4d39-4703-9fc7-cc103b3722c9
		summarizeBy: none
		sourceColumn: Product

		annotation SummarizationSetBy = Automatic

	column 'Discount Band'
		dataType: string
		lineageTag: 5f0fe2f3-f512-4226-b7fa-3893d931301e
		summarizeBy: none
		sourceColumn: Discount Band

		annotation SummarizationSetBy = Automatic

	column 'Units Sold'
		dataType: double
		lineageTag: e4a17300-fc42-405e-aef6-363e6587d587
		summarizeBy: sum
		sourceColumn: Units Sold

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Manufacturing Price'
		dataType: int64
		formatString: 0
		lineageTag: 01542e8b-3140-4a5d-be07-a6f5c3cbe24e
		summarizeBy: sum
		sourceColumn: Manufacturing Price

		annotation SummarizationSetBy = Automatic

	column 'Sale Price'
		dataType: int64
		formatString: 0
		lineageTag: b2e270fc-586c-40c6-92d7-b593ff57c4a6
		summarizeBy: sum
		sourceColumn: Sale Price

		annotation SummarizationSetBy = Automatic

	column 'Gross Sales'
		dataType: double
		lineageTag: a5d1cfc2-9398-484d-9a1d-3ba2a9e78f5e
		summarizeBy: sum
		sourceColumn: Gross Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Discounts
		dataType: double
		lineageTag: 8046f765-3a31-439e-8542-35d84d0a8709
		summarizeBy: sum
		sourceColumn: Discounts

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Sales
		dataType: double
		lineageTag: 52bdeaed-c689-4879-8a45-483ca8381fa6
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column COGS
		dataType: double
		lineageTag: 51fee7f7-fe6d-45ac-9f73-6a73c5e314d1
		summarizeBy: sum
		sourceColumn: COGS

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 0e364f34-7330-408f-b703-fd50d0dc4ea0
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

		annotation __PBI_SemanticLinks = [{"LinkTarget":{"TableName":"Sheet1","TableItemName":"Profit (groups)","ObjectType":4},"LinkType":"UsedInGroup"}]

	column Date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 5edb09df-f88b-4f79-b0e2-c7426dfab334
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: d360beb2-d1b5-41a5-b751-d2e29e7c90d9
			defaultHierarchy: LocalDateTable_766cebae-087a-4bc6-9843-5f7a836c3c30.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Month Number'
		dataType: int64
		formatString: 0
		lineageTag: 5c58bcf0-0d73-4433-b9c5-942a4a66732f
		summarizeBy: sum
		sourceColumn: Month Number

		annotation SummarizationSetBy = Automatic

	column 'Month Name'
		dataType: string
		lineageTag: 020f885c-073b-486a-a5d0-1dfdfefb76d2
		summarizeBy: none
		sourceColumn: Month Name

		annotation SummarizationSetBy = Automatic

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 9c65d441-79a8-4338-86fa-f9a74d59734a
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column 'Profit (groups)' =
			SWITCH(
				TRUE,
				ISBLANK('Sheet1'[Profit]),
				"(Blank)",
				'Sheet1'[Profit] IN {-40617.5,
					-38046.25,
					-35550,
					-35262.5,
					-33522.5},
				"-40617.5 & -38046.25 & -35550 & -35262.5 & -33522.5",
				"Other"
			)
		lineageTag: 63fb7e51-9746-4c8b-b45f-acd26da45095
		summarizeBy: none

		extendedProperty GroupingMetadata =
				{
				  "version": 0,
				  "groupedColumns": [
				    {
				      "Column": {
				        "Expression": {
				          "SourceRef": {
				            "Entity": "Sheet1"
				          }
				        },
				        "Property": "Profit"
				      }
				    }
				  ]
				}

		annotation GroupingDesignState = {"Version":0,"Sources":[{"Name":"s","Entity":"Sheet1"}],"GroupedColumns":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"Profit"}}],"GroupItems":[{"DisplayName":"(Blank)","BlankDefaultPlaceholder":true},{"DisplayName":"-40617.5 & -38046.25 & -35550 & -35262.5 & -33522.5","Expression":{"In":{"Expressions":[{"Column":{"Expression":{"SourceRef":{"Source":"s"}},"Property":"Profit"}}],"Values":[[{"Literal":{"Value":"-40617.5D"}}],[{"Literal":{"Value":"-38046.25D"}}],[{"Literal":{"Value":"-35550D"}}],[{"Literal":{"Value":"-35262.5D"}}],[{"Literal":{"Value":"-33522.5D"}}]]}}},{"DisplayName":"Other"}]}

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Sheet1 = m
		mode: import
		source =
				let
				 Source = Excel.Workbook(File.Contents("C:\Program Files\WindowsApps\Microsoft.MicrosoftPowerBIDesktop_2.141.1451.0_x64__8wekyb3d8bbwe\bin\SampleData\Financial Sample.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Segment", type text}, {"Country", type text}, {"Product", type text}, {"Discount Band", type text}, {"Units Sold", type number}, {"Manufacturing Price", Int64.Type}, {"Sale Price", Int64.Type}, {"Gross Sales", type number}, {"Discounts", type number}, {"Sales", type number}, {"COGS", type number}, {"Profit", type number}, {"Date", type date}, {"Month Number", Int64.Type}, {"Month Name", type text}, {"Year", Int64.Type}})
				in
				 #"Changed Type"

	annotation PBI_ResultType = Table

